ExampleDDDArchitecture.MVC/ViewModels/CotacaoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExampleDDDArchitecture.MVC.ViewModels
{
    public class CotacaoViewModel
    {
        [Key]
        [Display(Name = "Código da Cotação")]
        public int CotacaoId { get; set; }

        [Required(ErrorMessage="Preencha o campo Tempo de Ligacao!")]
        [Display(Name = "Tempo de Ligação")]
        public int TempoLigacao { get; set; }

        [DataType(DataType.Currency)]
        [Display(Name = "Com Fale Mais")]
        public decimal ComFaleMais { get; set; }

        [DataType(DataType.Currency)]
        [Display(Name = "Sem Fale Mais")]
        public decimal SemFaleMais { get; set; }

        [ScaffoldColumn(false)]
        public DateTime DataCotacao { get; set; }

        //public int ProdutoId { get; set; }

        [Display(Name = "Origem DDD")]
        [Required(ErrorMessage = "Preencha o campo Origem DDD!")]
        [MaxLength(3, ErrorMessage = "Obrigatório ter 3 caracteres! Ex: 011"), MinLength(3, ErrorMessage = "Obrigatório ter 3 caracteres! Ex: 011")]
        [ForeignKey("ProdutoViewModel")]
        [Column(Order = 1)]
        public string OrigemDDD { get; set; }

        [Display(Name = "Destino DDD")]
        [Required(ErrorMessage = "Preencha o campo Destino DDD!")]
        [MaxLength(3, ErrorMessage = "Obrigatório ter 3 caracteres! Ex: 011"), MinLength(3, ErrorMessage = "Obrigatório ter 3 caracteres! Ex: 016")]
        [ForeignKey("ProdutoViewModel")]
        [Column(Order = 2)]
        public string DestinoDDD { get; set; }

        [Display(Name = "Tipo de Plano")]
        [Required(ErrorMessage = "Escolha o plano desejado!")]
        public int PlanoId { get; set; }

        public virtual ProdutoViewModel Produto { get; set; }

        public virtual PlanoViewModel Plano { get; set; }
    }
}

ExampleDDDArchitecture.MVC/Controllers/CotacaoController.cs
using AutoMapper;
using ExampleDDDArchitecture.Application.Interface;
using ExampleDDDArchitecture.Domain.Entities;
using ExampleDDDArchitecture.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExampleDDDArchitecture.MVC.Controllers
{
    public class CotacaoController : Controller
    {
        private readonly ICotacaoAppService _cotacaoApp;
        //private readonly IProdutoAppService _produtoApp;
        private readonly IPlanoAppService _planoApp;

        public CotacaoController(ICotacaoAppService cotacaoApp, IPlanoAppService planoApp)
        {
            _cotacaoApp = cotacaoApp;
            //_produtoApp = produtoApp;
            _planoApp = planoApp;
        }

        // GET: cotacao
        public ActionResult Index()
        {
            var cotacaoViewModel = Mapper.Map<IEnumerable<Cotacao>, IEnumerable<CotacaoViewModel>>(_cotacaoApp.GetAll());

            return View(cotacaoViewModel);
        }

        // GET: Cotacao/Details/5
        public ActionResult Details(int id)
        {
            var cotacao = _cotacaoApp.GetById(id);
            var cotacaoViewModel = Mapper.Map<Cotacao, CotacaoViewModel>(cotacao);

            return View(cotacaoViewModel);
        }

        // GET: Produtos/Create
        public ActionResult Create()
        {
            var lstPlano = _planoApp.GetAll();

            IEnumerable<SelectListItem> SliPlano = lstPlano.ToList().Select(i => new SelectListItem()
            {
                Text = i.TipoPlano,
                Value = i.PlanoId.ToString(),
            });

            ViewBag.TiposPlanos = SliPlano;

            return View();
        }

        // POST: Produtos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CotacaoViewModel cotacao)
        {
            if (ModelState.IsValid)
            {
                cotacao.DataCotacao = DateTime.Now;
                var cotacaoDomain = Mapper.Map<CotacaoViewModel, Cotacao>(cotacao);
                _cotacaoApp.Add(cotacaoDomain);

                return RedirectToAction("Index");
            }

            return View(cotacao);
        }

        // GET: Produtos/Edit/5
        public ActionResult Edit(int id)
        {
            var cotacao = _cotacaoApp.GetById(id);
            var cotacaoViewModel = Mapper.Map<Cotacao, CotacaoViewModel>(cotacao);

            return View(cotacaoViewModel);
        }

        // POST: Produtos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CotacaoViewModel cotacaoViewModel)
        {
            if (ModelState.IsValid)
            {
                var cotacaoDomain = Mapper.Map<CotacaoViewModel, Cotacao>(cotacaoViewModel);
                _cotacaoApp.Update(cotacaoDomain);

                return RedirectToAction("Index");
            }

            return View(cotacaoViewModel);
        }

        // GET: Produtos/Delete/5
        public ActionResult Delete(int id)
        {
            var cotacao = _cotacaoApp.GetById(id);
            var cotacaoViewModel = Mapper.Map<Cotacao, CotacaoViewModel>(cotacao);

            return View(cotacaoViewModel);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var cotacao = _cotacaoApp.GetById(id);
            _cotacaoApp.Remove(cotacao);

            return RedirectToAction("Index");
        }

        public ActionResult ValidateOrigemDDDDestinoDDD(string origemDDD, string destinoDDD)
        {
            var produto = _cotacaoApp.CheckIfTariffExist(origemDDD, destinoDDD);

            return Content(produto.ToString(), "text/plain");
        }

        public ActionResult NewQuotation(string origemDDD, string destinoDDD, int plano, int tempo)
        {
            var cotacaoDomain = _cotacaoApp.ToDoQuotation(origemDDD, destinoDDD, plano, tempo);

            var cotacaoViewModel = Mapper.Map<Cotacao, CotacaoViewModel>(cotacaoDomain);

            return Json(cotacaoViewModel, JsonRequestBehavior.AllowGet);
        }
    }
}

ExampleDDDArchitecture.MVC/Views/Cotacao/Create.cshtml
@model ExampleDDDArchitecture.MVC.ViewModels.CotacaoViewModel


@{
    ViewBag.Title = "Fazendo cotação";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Cotação</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group ">
            @Html.LabelFor(model => model.Plano.TipoPlano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PlanoId", (IEnumerable<SelectListItem>)ViewBag.TiposPlanos, new { @id = "cbbPlano", @class = "btn btn-default dropdown-toggle" })
                @Html.ValidationMessageFor(model => model.PlanoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrigemDDD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrigemDDD, new { htmlAttributes = new { @id = "txtOrigem", @class = "form-control", @placeholder = "Ex: 011", @maxlength = "3" } })
                @Html.ValidationMessageFor(model => model.OrigemDDD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DestinoDDD, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DestinoDDD, new { htmlAttributes = new { @id = "txtDestino", @class = "form-control", @placeholder = "Ex: 016", @maxlength = "3" } })
                @Html.ValidationMessageFor(model => model.DestinoDDD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempoLigacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempoLigacao, new { htmlAttributes = new { @id = "txtTempo", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TempoLigacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ComFaleMais, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComFaleMais, new { htmlAttributes = new { @id = "txtComFaleMais", @class = "form-control", @readonly = true } })
                @Html.ValidationMessageFor(model => model.ComFaleMais, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SemFaleMais, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SemFaleMais, new { htmlAttributes = new { @id = "txtSemFaleMais", @class = "form-control", @readonly = true } })
                @Html.ValidationMessageFor(model => model.SemFaleMais, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" id="btnCotacao" value="Fazer Cotação" class="btn btn-success" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnGerarCotacao" value="Gravar Cotação" class="btn btn-primary" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">
    $(document).ready(function () {

        $('#txtDestino').change(function () {

            var txtOrigem = $('#txtOrigem').val();
            var txtDestino = $('#txtDestino').val();

            if (txtOrigem == '') {
                alert('Preencha o campo Origem DDD!');
            }
            else if (txtDestino == '') {
                alert('Preencha o campo Destino DDD!');
            }
            else {
                $.ajax({
                    type: 'GET',
                    data: { origemDDD: txtOrigem, destinoDDD: txtDestino },
                    url: '@Url.Action("ValidateOrigemDDDDestinoDDD", "Cotacao")',
                    beforeSend: function () {
                        //alert('Verificando...');
                    },
                    success: function (result) {
                        //TO DO - mostrar na tela que os campos origem e destino são válidos ou inválidos.
                        if (result > 0) {
                            $('#txtOrigem').addClass('alert-success');
                            $('#txtDestino').addClass('alert-success');
                        }
                        else {
                            $('#txtOrigem').addClass('alert-danger');
                            $('#txtDestino').addClass('alert-danger');
                        }
                        
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert("Ajax Failed!!!");
                    }
                });
            }
        });

        $('#btnCotacao').click(function () {

            var txtOrigem = $('#txtOrigem').val();
            var txtDestino = $('#txtDestino').val();
            var cbbPlano = $('#cbbPlano').val();
            var txtTempo = $('#txtTempo').val();

            if (txtOrigem == '') {
                alert('Preencha o campo Origem DDD!');
                //$('#txtOrigem').addClass('alert-danger');
            }
            else if (txtDestino == '') {
                alert('Preencha o campo Destino DDD!');
            }
            else if (cbbPlano == '') {
                alert('Escolha um Tipo de Plano!');
            }
            else if (txtTempo == '') {
                alert('Preencha o campo Tempo de Ligação!');
            }
            else {
                $.ajax({
                    type: 'GET',
                    dataType: 'json',
                    contentType: 'application/json',
                    data: { origemDDD: txtOrigem, destinoDDD: txtDestino, plano: cbbPlano, tempo: txtTempo },
                    url: '@Url.Action("NewQuotation", "Cotacao")',
                    beforeSend: function () {
                        //alert('Fazendo Cotação...');
                    },
                    success: function (result) {
                        var SemfaleMais = parseFloat(result.SemFaleMais);
                        var ComFaleMais = parseFloat(result.ComFaleMais);

                        $('#txtSemFaleMais').val(SemfaleMais.toFixed(2));
                        $('#txtComFaleMais').val(ComFaleMais.toFixed(2));
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert("Ajax Failed!!!");
                    }
                });
            }
        });

    });
</script>

ExampleDDDArchitecture.MVC/Views/Cotacao/Index.cshtml
@model IEnumerable<ExampleDDDArchitecture.MVC.ViewModels.CotacaoViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr class="alert-info">
        <th>
            @Html.DisplayNameFor(model => model.CotacaoId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Plano.TipoPlano)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrigemDDD)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DestinoDDD)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TempoLigacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ComFaleMais)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SemFaleMais)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CotacaoId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Plano.TipoPlano)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrigemDDD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DestinoDDD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TempoLigacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ComFaleMais)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SemFaleMais)
        </td>
        <td>
            @Html.ActionLink("Editar ?", "Edit", new { id=item.CotacaoId }) |
            @Html.ActionLink("Detalhes ?", "Details", new { id=item.CotacaoId }) |
            @Html.ActionLink("Apagar ?", "Delete", new { id=item.CotacaoId })
        </td>
    </tr>
}

</table>